# Desativa o prefixo antigo (C-b)
unbind C-b

# Define o novo prefixo (C-a)
set-option -g prefix C-a

# Envia C-a para o terminal quando pressionado duas vezes
bind-key C-a send-prefix

# Desativa os splits antigos e desconfortáveis
unbind %
unbind '"'

# Novos splits: v (vertical) e h (horizontal)
bind v split-window -h
bind h split-window -v

# Fecha paineis (x) sem pedir confirmacao
bind x kill-pane
